version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true
install:
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./EventBus.Sqs/EventBus.Sqs.csproj --verbosity m
build_script:
  - cmd: dotnet build ./EventBus.Sqs/EventBus.Sqs.csproj
after_build:

on_finish :

deploy: off